# Generated by Django 4.0 on 2021-12-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='timeslots',
            field=models.CharField(choices=[('07:00', '07:50'), ('07:50', '08:40'), ('08:40', '09:30'), ('09:40', '10:30'), ('10:40', '11:30'), ('12:30', '13:20'), ('13:20', '14:10'), ('14:20', '15:10'), ('15:10', '16:00'), ('16:10', '17:00')], max_length=20),
        ),
    ]
