# Generated by Django 4.0 on 2021-12-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0002_alter_session_timeslots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='timeslots',
            field=models.CharField(choices=[('07:00', '07:50'), ('07:50', '08:40'), ('08:40', '09:30'), ('09:40', '10:30'), ('10:40', '11:30')], max_length=20),
        ),
    ]
