# Generated by Django 4.0 on 2021-12-21 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0003_alter_session_timeslots'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='alogrithm',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='time_to_create',
            field=models.FloatField(default=0),
        ),
    ]
