# Generated by Django 4.0 on 2021-12-21 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0004_timetable_alogrithm_timetable_time_to_create'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='alogrithm',
            new_name='algorithm',
        ),
    ]
